media_app/media/urls.py
from django.urls import path
from media.views import *

app_name = "media"

urlpatterns = [
    path(r"media-file-stream/", ViewMediaFileStream.as_view(), name="file-stream"),
    path(r"media-update-duration/", ViewMediaUpdateDuration.as_view(), name="update-duration"),
    path(r"media-update-play-count/", ViewMediaUpdatePlayCount.as_view(), name="update-play-count"),
    path(r"player", ViewPlayer.as_view(), name="player"),
]

media_app/media_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("media/", include("media.urls"))
]

media_app/media/models.py
from datetime import timedelta
from hashlib import md5
from pathlib import Path
from urllib.parse import urlparse, unquote
from urllib.request import urlopen
from django.db import models


class Tag(models.Model):
    class Meta:
        ordering = ("title",)

    created = models.DateTimeField(auto_now_add=True, editable=False)
    updated = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=200, blank=False, null=False)
    description = models.TextField(blank=True, null=False, default="")

    def __str__(self):
        return self.title

    def __repr__(self):
        return f"<{self.__class__.__name__} pk={self.pk} title=\"{self.title[:50]}>\""


class Media(models.Model):
    chunk_size = 1024 * 10

    created = models.DateTimeField(auto_now_add=True, editable=False)
    updated = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=200, blank=False, null=False)
    path = models.CharField(max_length=200, blank=False, null=False, unique=True)
    description = models.TextField(blank=True, null=False, default="")
    tags = models.ManyToManyField(Tag)
    play_count = models.IntegerField(blank=False, null=False, default=0)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title

    def __repr__(self):
        return f"<{self.__class__.__name__} pk={self.pk} title=\"{self.title[:50]}>\""
    
    def get_processed_path(self):
        raise NotImplementedError()
    
    def get_fd_iterator(self):
        raise NotImplementedError()


class Audio(Media):
    chunk_size = 1024 * 1024

    file_size = models.IntegerField(blank=False, null=False, default=0)
    md5_hex = models.CharField(max_length=200, blank=False, null=False, unique=True)
    duration = models.DurationField(blank=False, null=False, default=timedelta(seconds=0))
    
    def get_processed_path(self):
        if self.path.startswith("file://"):
            file_path = Path(unquote(urlparse(self.path).path))
        elif self.path.startswith("/home/"):
            file_path = Path(self.path)
        else:
            raise NotImplementedError()
        return file_path
    
    def get_fd_iterator(self):
        chunk_size = self.__class__.chunk_size
        with self.get_processed_path().open("rb") as file:
            if self.md5_hex == "":
                md5_buf = md5(b"")
                chunk = file.read(chunk_size)
                while chunk:
                    md5_buf.update(chunk)
                    yield chunk
                    chunk = file.read(chunk_size)
                self.md5_hex = md5_buf.hexdigest()
                self.save()
            else:
                chunk = file.read(chunk_size)
                while chunk:
                    yield chunk
                    chunk = file.read(chunk_size)
    

class Radio(Media):
    chunk_size = 1024

    quality = models.CharField(max_length=1, choices=(("l", "low"), ("m", "medium"), ("h", "high")))

    def get_processed_path(self):
        return urlparse(self.path)
    
    def get_fd_iterator(self):
        chunk_size = self.__class__.chunk_size
        with urlopen(self.get_processed_path().geturl()) as file:
            chunk = file.read(chunk_size)
            while chunk:
                yield chunk
                chunk = file.read(chunk_size)


class Video(Media):
    chunk_size = 1024 * 1024

    file_size = models.IntegerField(blank=False, null=False, default=0)
    md5_hex = models.CharField(max_length=200, blank=False, null=False, unique=True)
    duration = models.DurationField(blank=False, null=False, default=timedelta(seconds=0))
    
    def get_processed_path(self):
        if self.path.startswith("file://"):
            file_path = Path(unquote(urlparse(self.path).path))
        elif self.path.startswith("/home/"):
            file_path = Path(self.path)
        else:
            raise NotImplementedError()
        return file_path
    
    def get_fd_iterator(self):
        chunk_size = self.__class__.chunk_size
        with self.get_processed_path().open("rb") as file:
            if self.md5_hex == "":
                md5_buf = md5(b"")
                chunk = file.read(chunk_size)
                while chunk:
                    md5_buf.update(chunk)
                    yield chunk
                    chunk = file.read(chunk_size)
                self.md5_hex = md5_buf.hexdigest()
                self.save()
            else:
                chunk = file.read(chunk_size)
                while chunk:
                    yield chunk
                    chunk = file.read(chunk_size)

media_app/media/views.py
from datetime import timedelta
from django.conf import settings
from django.views import View
from django.http.request import HttpRequest
from django.http.response import StreamingHttpResponse, JsonResponse, HttpResponse
from media.models import Audio, Radio, Video


Media = Audio | Radio | Video


class ViewBaseFileStream(View):
    content_type = "application/octet-stream"

    def get(self, request: HttpRequest) -> StreamingHttpResponse:
        object = self.get_object()
        if object is None:
            return StreamingHttpResponse(iter([b""]))
        response = StreamingHttpResponse(
            object.get_fd_iterator(),
            content_type=self.content_type,
        )
        response = self.update_response_headers(object, response)
        return response

    def get_object(self) -> Media:
        raise NotImplementedError()

    def update_response_headers(
        self, object: Media, response: StreamingHttpResponse
    ) -> StreamingHttpResponse:
        return response


class ViewMediaFileStream(ViewBaseFileStream):
    def get_object(self) -> Media | None:
        media_id = self.request.GET.get("id")
        media_type = self.request.GET.get("type")
        match media_type:
            case "audio":
                media_class = Audio
            case "radio":
                media_class = Radio
            case "video":
                media_class = Video
            case _:
                raise NotImplementedError()
        return media_class.objects.filter(id=media_id).first()

    def update_response_headers(
        self, object: Media, response: StreamingHttpResponse
    ) -> StreamingHttpResponse:
        if isinstance(object, (Audio, Video)):
            fsize = object.get_processed_path().stat().st_size
            if object.file_size == 0:
                object.file_size = fsize
                object.save()
            response["Accept-Ranges"] = "bytes"
            response["Content-Length"] = fsize
            response["Content-Range"] = f"bytes 0-{fsize - 1}/{fsize}"
            return response
        elif isinstance(object, Radio):
            return response
        else:
            raise NotImplementedError()


class ViewMediaUpdateDuration(View):
    def post(self, request: HttpRequest) -> JsonResponse:
        media_id = request.POST.get("id")
        media_type = request.POST.get("type")
        dur = request.POST.get("duration")
        if dur is None:
            return JsonResponse(dict(), status=400)
        duration = int(float(dur))
        match media_type:
            case "audio":
                media_class = Audio
            case "video":
                media_class = Video
            case _:
                raise NotImplementedError()
        media = media_class.objects.get(id=media_id)
        media.duration = timedelta(seconds=duration)
        media.save()
        return JsonResponse(dict(), status=200)


class ViewMediaUpdatePlayCount(View):
    def post(self, request: HttpRequest) -> JsonResponse:
        media_id = request.POST.get("id")
        media_type = request.POST.get("type")
        if media_id is None:
            return JsonResponse(dict(), status=400)
        match media_type:
            case "audio":
                media_class = Audio
            case "radio":
                media_class = Radio
            case "video":
                media_class = Video
            case _:
                raise NotImplementedError()
        media = media_class.objects.get(id=media_id)
        media.play_count = media.play_count + 1
        media.save()
        return JsonResponse(dict(), status=200)


class ViewPlayer(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        from django.template.loader import render_to_string

        content = render_to_string(
            "media/player.html", dict(stream_backend_url=settings.STREAM_BACKEND_URL)
        )
        return HttpResponse(content)

media_app/media/templates/media/admin/audio_change_form.html
{% extends "media/admin/media_change_form.html" %}


{% block media_type %}
    global.media_type = "audio";
{% endblock media_type %}

media_app/media/templates/media/admin/audio_change_list.html
{% extends "media/admin/media_change_list.html" %}


{% block media_type %}
    global.media_type = "audio";
{% endblock media_type %}

media_app/media/templates/media/admin/media_change_form.html
{% extends "admin/change_form.html" %}
{% load static md5static %}


{% block extrahead %}
{{ block.super }}
<script src="{% static "media/js/common.js" %}" type="text/javascript"></script>
<script>
    var global = {
        urls: {
            player: "{% url "media:player" %}",
            worker_src_url: "{% md5static "media/js/worker.js" %}",
        },
    };
    {% block media_type %}{% endblock media_type %}    
</script>
<script type="text/javascript" src="{% static "media/js/host_handler.js" %}"></script>
{% endblock extrahead %}

media_app/media/templates/media/admin/media_change_list.html
{% extends "admin/change_list.html" %}
{% load static md5static %}


{% block extrahead %}
{{ block.super }}
<style>
    tr.playing {
        background: var(--selected-row);
    }
</style>
<script src="{% static 'media/js/common.js' %}" type="text/javascript"></script>
<script>
    var global = {
        urls: {
            player: "{% url 'media:player' %}",
            worker_src_url: "{% md5static 'media/js/worker.js' %}",
        },  
    };
    {% block media_type %}{% endblock media_type %}    
</script>
<script type="text/javascript" src="{% md5static 'media/js/host_handler.js' %}"></script>
{% endblock extrahead %}

media_app/media/templates/media/admin/radio_change_form.html
{% extends "media/admin/media_change_form.html" %}


{% block media_type %}
    global.media_type = "radio";
{% endblock media_type %}

media_app/media/templates/media/admin/radio_change_list.html
{% extends "media/admin/media_change_list.html" %}


{% block media_type %}
    global.media_type = "radio";
{% endblock media_type %}

media_app/media/templates/media/admin/video_change_form.html
{% extends "media/admin/media_change_form.html" %}


{% block media_type %}
    global.media_type = "video";
{% endblock media_type %}

media_app/media/templates/media/admin/video_change_list.html
{% extends "media/admin/media_change_list.html" %}


{% block media_type %}
    global.media_type = "video";
{% endblock media_type %}